image: continuumio/miniconda3:latest

pipelines:
  default:
    - step:
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'."
  branches:
    develop:
      - step:
          script:
            - echo "This script runs only on commit to the develop branch."
            - conda env create --file env/scpy.yml
            - conda activate scpy
            - pip install -e .
            - conda install pytest
            - pytest
