image: continuumio/miniconda3:latest

pipelines:
  default:
    - step:
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'."
  branches:
    develop:
      - step:
          script:
            - echo "This script runs only on commit to the develop branch."
            - conda config --add channels cantera
            - conda config --add channels spectrocat
            - conda config --add channels conda-forge
            - conda config --set channel_priority strict
            - conda env update -n root --file env/bitbucket-env.yml
            - pip install -e .
            - pytest
