image: continuumio/miniconda3:latest

pipelines:
  default:
    - step:
        script:
          - echo "Runs on all branches that don't have any specific pipeline assigned in 'branches'."
  branches:
    develop:
      - step:
          caches:
            - conda
          script:
            - echo "Runs only on commit to the develop branch."
            - conda update -n base conda
            - conda env update -n scpy --quiet --file env/scpy.yml
            - conda activate scpy
            - pip install -e .
            - conda install pytest
            - pytest --nodisplay
definitions:
  caches:
    conda:  ~/.conda/envs/scpy/bin
