image: spectrocat/python37:1

pipelines:
  default:
  - step:
      script:
      - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'."
  branches:
    master:
    - step:
        script:
        - echo "This script runs only on commit to the master branch."
        - pip install -e .
        - pytest tests/
