image: continuumio/miniconda3

pipelines:
  default:
  - step:
      script:
      - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'."
  branches:
    master:
    - step:
        script:
        - echo "This script runs only on commit to the master branch."
        - conda config --prepend channels conda-forge 
        - conda install --yes --file requirements.txt
        - pip install -e .
        - cd tests
        - pytest .
