image: continuumio/miniconda3

pipelines:
  default:
  - step:
      script:
      - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'."
  branches:
    master:
    - step:
        script:
        - echo "This script runs only on commit to the master branch."
        - apt-get update && apt-get install libgl1-mesa-glx libglib2.0-0 -y
        #- conda config --prepend channels conda-forge
        #- conda install --yes --file requirements.txt
        - conda env create -f scp37env.yml
        - source activate scp37
        - pip install -e .
        - cd tests
        - pytest .
