name: scpy
channels:
- conda
- conda-forge
dependencies:
- python=3.6
- setuptools
- ipython
- matplotlib
- pyqt
- scipy
- setuptools_scm
- xlrd
- pandas
- requests
- pytest
- jupyter
- scikit-image
- nb_conda
- pytest-runner
- sphinx
- pip:
   - sphinx_rtd_theme
   - sphinx-gallery
   - nbsphinx
   - numpydoc
