{% set name = "spectrochempy" %}
{% set version = "0.1.16" %}

# see this  for a description of the sections
# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: ../../
  git_rev: "{{ version }}"

python:
  - 3.6
  - 3.7
  - 3.8

build:
  number: 0
  noarch: generic
  entry_points:
    - scpy=spectrochempy.scripts.launch_api:main
  script:
    - python -m pip install . -vv
    - jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib

requirements:
  host:
    - pip
    - python
  build:
    - python           {{ python }}
    - setuptools
    - setuptools_scm
  run:
    - python
    - numpy
    - matplotlib
    - traitlets
    - pint             0.9
    - quaternion
    - scipy
    - colorama
    - setuptools_scm
    - ipython
    - jupyterlab
    - ipympl
    - nodejs
    - ipykernel
    - ipywidgets
    - widgetsnbextension
    - xlrd
    - numba
    - pandas
    - cantera
    - quadprog
    - pyqt
    - tqdm
    - twine

test:
  imports:
    - scp_data
    - spectrochempy
    - spectrochempy.core
    - spectrochempy.core.analysis
    - spectrochempy.core.dataset
    - spectrochempy.core.fitting
    - spectrochempy.core.plotters
    - spectrochempy.core.processors
    - spectrochempy.core.project
    - spectrochempy.core.readers
    - spectrochempy.core.readers.nmr
    - spectrochempy.core.scripts
    - spectrochempy.core.writers
    - spectrochempy.databases
    - spectrochempy.scripts
    - spectrochempy.units
    - spectrochempy.utils
    - spectrochempy.widgets

  commands:
    - scpy --help

about:
  home: "https://redmine.spectrochempy.fr"
  license: CeCILL-B
  license_family: OTHER
  summary: "Processing, analysis and modelling Spectroscopic data for Chemistry with Python"
  doc_url: "https://www.spectrochempy.fr"
  dev_url: "https://bitbucket.org/spectrocat/spectrochempy"

extra:
  recipe-maintainers:
    - fernandezc