package:
  name: spectrochempy
  version: 0.1.a7

source:
  path: ../../

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm

  run:
    - python        3.7.*
    - numpy
    - scipy
    - matplotlib
    - traitlets
    # some other useful package
    - pandas
    - xlrd
    - requests
    # mainly for install and a bit more...
    - setuptools_scm
    # need this, because the API is mainly designed to run in Jupyter notebook
    - ipython
    - jupyter
    - jupyterlab
    - ipykernel
    - ipywidgets
    - jupyter_nbextensions_configurator
    - ipyparallel
    - ipympl
    - widgetsnbextension
    - nodejs
    - conda-build
    - jupytext
    - nb_conda
    # for testing
    - pytest
    - pytest-runner
    - pytest-cov
    - pytest-xdist
    - pytest-console-scripts
    - pytest-qt
    - scikit-image
    # for docs
    - sphinx
    - sphinx_rtd_theme
    - sphinx-gallery
    - numpydoc
    - nbsphinx
    - jupyter_sphinx
    - nbconvert
    # for matplotlib backend and future gui
    - pyqt

#test:
  # Python imports
#  imports:
#    - spectrochempy
#    - spectrochempy.api

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

about:
  home: http://www-lcs.ensicaen.fr/cfnews/spectrochempy/html
  license: CeCILL 2.1 License
  summary: 'SpectroChemPy is a framework for processing, analysing and modelling Spectroscopic data for Chemistry with Python'
  license_family: OTHER

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
