package:
  name: spectrochempy
  version: 0.1.b1

source:
  path: ../../

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm

  run:
    - python        3.6.*
    - matplotlib
    - traitlets
    - numpy
    - scipy
    - pandas
    - xlrd
    - ipython
    - ipykernel
    - nb_conda
    - setuptools_scm

#test:
  # Python imports
#  imports:
#    - spectrochempy
#    - spectrochempy.api

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

about:
  home: http://www-lcs.ensicaen.fr/cfnews/spectrochempy/html
  license: CeCILL 2.1 License
  summary: 'SpectroChemPy is a framework for processing, analysing and modelling Spectroscopic data for Chemistry with Python'
  license_family: OTHER

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
